# Table of Contents
 <p>

In [1]:
import pandas as pd

audit = pd.read_csv(r'audit_risk.csv')
names = ['Sector_score','LOCATION_ID','PARA_A','Score_A','Risk_A','PARA_B','Score_B','Risk_B','TOTAL	numbers	Score_B','Risk_C','oney_Value','Score_MV','Risk_D','District_Loss','PROB','RiSk_E','History','Prob','Risk_F','Score','Inherent_Risk','CONTROL_RISK','Detection_Risk','Audit_Risk','Risk']

In [2]:
audit.head()

,Sector_score,LOCATION_ID,PARA_A,Score_A,Risk_A,PARA_B,Score_B,Risk_B,TOTAL,numbers,...,RiSk_E,History,Prob,Risk_F,Score,Inherent_Risk,CONTROL_RISK,Detection_Risk,Audit_Risk,Risk
0,3.89,23,4.18,0.6,2.508,2.50,0.2,0.500,6.68,5.0,...,0.4,0,0.2,0.0,2.4,8.574,0.4,0.5,1.7148,1
1,3.89,6,0.00,0.2,0.000,4.83,0.2,0.966,4.83,5.0,...,0.4,0,0.2,0.0,2.0,2.554,0.4,0.5,0.5108,0
2,3.89,6,0.51,0.2,0.102,0.23,0.2,0.046,0.74,5.0,...,0.4,0,0.2,0.0,2.0,1.548,0.4,0.5,0.3096,0
3,3.89,6,0.00,0.2,0.000,10.80,0.6,6.480,10.80,6.0,...,0.4,0,0.2,0.0,4.4,17.530,0.4,0.5,3.5060,1
4,3.89,6,0.00,0.2,0.000,0.08,0.2,0.016,0.08,5.0,...,0.4,0,0.2,0.0,2.0,1.416,0.4,0.5,0.2832,0

In [3]:
audit.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
Sector_score,776.0,20.184536,24.319017,1.85,2.3700,3.8900,55.5700,59.8500
PARA_A,776.0,2.450194,5.678870,0.00,0.2100,0.8750,2.4800,85.0000
Score_A,776.0,0.351289,0.174055,0.20,0.2000,0.2000,0.6000,0.6000
Risk_A,776.0,1.351029,3.440447,0.00,0.0420,0.1750,1.4880,51.0000
PARA_B,776.0,10.799988,50.083624,0.00,0.0000,0.4050,4.1600,1264.6300
Score_B,776.0,0.313144,0.169804,0.20,0.2000,0.2000,0.4000,0.6000
Risk_B,776.0,6.334008,30.072845,0.00,0.0000,0.0810,1.8405,758.7780
TOTAL,776.0,13.218481,51.312829,0.00,0.5375,1.3700,7.7075,1268.9100
numbers,776.0,5.067655,0.264449,5.00,5.0000,5.0000,5.0000,9.0000
Score_B.1,776.0,0.223711,0.080352,0.20,0.2000,0.2000,0.2000,0.6000
Risk_C,776.0,1.152964,0.537417,1.00,1.0000,1.0000,1.0000,5.4000
Money_Value,775.0,14.137631,66.606519,0.00,0.0000,0.0900,5.5950,935.0300
Score_MV,776.0,0.290979,0.159745,0.20,0.2000,0.2000,0.4000,0.6000
Risk_D,776.0,8.265434,39.970849,0.00,0.0000,0.0180,2.2350,561.0180
District_Loss,776.0,2.505155,1.228678,2.00,2.0000,2.0000,2.0000,6.0000
PROB,776.0,0.206186,0.037508,0.20,0.2000,0.2000,0.2000,0.6000
RiSk_E,776.0,0.519072,0.290312,0.40,0.4000,0.4000,0.4000,2.4000
History,776.0,0.104381,0.531031,0.00,0.0000,0.0000,0.0000,9.0000
Prob,776.0,0.216753,0.067987,0.20,0.2000,0.2000,0.2000,0.6000
Risk_F,776.0,0.053608,0.305835,0.00,0.0000,0.0000,0.0000,5.4000
Score,776.0,2.702577,0.858923,2.00,2.0000,2.4000,3.2500,5.2000
Inherent_Risk,776.0,17.680612,54.740244,1.40,1.5835,2.2140,10.6635,801.2620
CONTROL_RISK,776.0,0.572680,0.444581,0.40,0.4000,0.4000,0.4000,5.8000
Detection_Risk,776.0,0.500000,0.000000,0.50,0.5000,0.5000,0.5000,0.5000
Audit_Risk,776.0,7.168158,38.667494,0.28,0.3167,0.5556,3.2499,961.5144
Risk,776.0,0.393041,0.488741,0.00,0.0000,0.0000,1.0000,1.0000

In [4]:
audit.describe()

,Sector_score,PARA_A,Score_A,Risk_A,PARA_B,Score_B,Risk_B,TOTAL,numbers,Score_B.1,...,RiSk_E,History,Prob,Risk_F,Score,Inherent_Risk,CONTROL_RISK,Detection_Risk,Audit_Risk,Risk
count,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,...,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,776.0,776.000000,776.000000
mean,20.184536,2.450194,0.351289,1.351029,10.799988,0.313144,6.334008,13.218481,5.067655,0.223711,...,0.519072,0.104381,0.216753,0.053608,2.702577,17.680612,0.572680,0.5,7.168158,0.393041
std,24.319017,5.678870,0.174055,3.440447,50.083624,0.169804,30.072845,51.312829,0.264449,0.080352,...,0.290312,0.531031,0.067987,0.305835,0.858923,54.740244,0.444581,0.0,38.667494,0.488741
min,1.850000,0.000000,0.200000,0.000000,0.000000,0.200000,0.000000,0.000000,5.000000,0.200000,...,0.400000,0.000000,0.200000,0.000000,2.000000,1.400000,0.400000,0.5,0.280000,0.000000
25%,2.370000,0.210000,0.200000,0.042000,0.000000,0.200000,0.000000,0.537500,5.000000,0.200000,...,0.400000,0.000000,0.200000,0.000000,2.000000,1.583500,0.400000,0.5,0.316700,0.000000
50%,3.890000,0.875000,0.200000,0.175000,0.405000,0.200000,0.081000,1.370000,5.000000,0.200000,...,0.400000,0.000000,0.200000,0.000000,2.400000,2.214000,0.400000,0.5,0.555600,0.000000
75%,55.570000,2.480000,0.600000,1.488000,4.160000,0.400000,1.840500,7.707500,5.000000,0.200000,...,0.400000,0.000000,0.200000,0.000000,3.250000,10.663500,0.400000,0.5,3.249900,1.000000
max,59.850000,85.000000,0.600000,51.000000,1264.630000,0.600000,758.778000,1268.910000,9.000000,0.600000,...,2.400000,9.000000,0.600000,5.400000,5.200000,801.262000,5.800000,0.5,961.514400,1.000000

In [5]:
audit.shape

(776, 27)

In [27]:
audit.drop(['Sector_score','LOCATION_ID'],axis=1).head()

,PARA_A,Score_A,Risk_A,PARA_B,Score_B,Risk_B,TOTAL,numbers,Score_B.1,Risk_C,...,RiSk_E,History,Prob,Risk_F,Score,Inherent_Risk,CONTROL_RISK,Detection_Risk,Audit_Risk,Risk
0,4.18,0.6,2.508,2.50,0.2,0.500,6.68,5.0,0.2,1.0,...,0.4,0,0.2,0.0,2.4,8.574,0.4,0.5,1.7148,1
1,0.00,0.2,0.000,4.83,0.2,0.966,4.83,5.0,0.2,1.0,...,0.4,0,0.2,0.0,2.0,2.554,0.4,0.5,0.5108,0
2,0.51,0.2,0.102,0.23,0.2,0.046,0.74,5.0,0.2,1.0,...,0.4,0,0.2,0.0,2.0,1.548,0.4,0.5,0.3096,0
3,0.00,0.2,0.000,10.80,0.6,6.480,10.80,6.0,0.6,3.6,...,0.4,0,0.2,0.0,4.4,17.530,0.4,0.5,3.5060,1
4,0.00,0.2,0.000,0.08,0.2,0.016,0.08,5.0,0.2,1.0,...,0.4,0,0.2,0.0,2.0,1.416,0.4,0.5,0.2832,0

In [71]:
#X = audit.drop('Sector_score',axis=1)
X =audit.drop(['Sector_score','LOCATION_ID'],axis=1) #LOCATION_ID这一列当中有的值是字符，不能做数值标准化运算，把它也去掉
#y = audit['Sector_score']
y = audit['District_Loss']  #应变量这一列因为是属于分类项，所以需要这一列的值是整数的，不能有小数的，比如可 选 District_Loss 这1列

In [72]:
X.describe().transpose().shape

(25, 8)

In [73]:
X.shape

(776, 25)

In [74]:
X.isnull().describe()

,PARA_A,Score_A,Risk_A,PARA_B,Score_B,Risk_B,TOTAL,numbers,Score_B.1,Risk_C,...,RiSk_E,History,Prob,Risk_F,Score,Inherent_Risk,CONTROL_RISK,Detection_Risk,Audit_Risk,Risk
count,776,776,776,776,776,776,776,776,776,776,...,776,776,776,776,776,776,776,776,776,776
unique,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
top,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
freq,776,776,776,776,776,776,776,776,776,776,...,776,776,776,776,776,776,776,776,776,776

In [75]:
X.isnull().any() #Money_Value列有缺失值，也不能进行数据标准化运算

PARA_A            False
Score_A           False
Risk_A            False
PARA_B            False
Score_B           False
Risk_B            False
TOTAL             False
numbers           False
Score_B.1         False
Risk_C            False
Money_Value        True
Score_MV          False
Risk_D            False
District_Loss     False
PROB              False
RiSk_E            False
History           False
Prob              False
Risk_F            False
Score             False
Inherent_Risk     False
CONTROL_RISK      False
Detection_Risk    False
Audit_Risk        False
Risk              False
dtype: bool

In [76]:
X=X.fillna(X.mean()) # 用平均值对缺失值 进行填充

In [77]:
X.isnull().any() #再次检查发现Money_Value列没有缺失值了

PARA_A            False
Score_A           False
Risk_A            False
PARA_B            False
Score_B           False
Risk_B            False
TOTAL             False
numbers           False
Score_B.1         False
Risk_C            False
Money_Value       False
Score_MV          False
Risk_D            False
District_Loss     False
PROB              False
RiSk_E            False
History           False
Prob              False
Risk_F            False
Score             False
Inherent_Risk     False
CONTROL_RISK      False
Detection_Risk    False
Audit_Risk        False
Risk              False
dtype: bool

In [78]:
y.isnull().any() #

False

In [79]:
#下面就可以进行标准化

In [80]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y)

In [81]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
#scaler = StandardScaler(copy=True, with_mean=True, with_std=True)
scaler.fit(X_train)

X_train = scaler.transform(X_train)

X_test = scaler.transform(X_test)


X_test

array([[-0.39668852, -0.84213153, -0.36086913, ...,  0.        ,
        -0.31629265, -0.77105159],
       [ 0.1802855 ,  1.49734603,  0.21129462, ...,  0.        ,
         0.22466143,  1.29693009],
       [ 0.21544736,  1.49734603,  0.24616333, ...,  0.        ,
        -0.31418041, -0.77105159],
       ...,
       [-0.04826653,  1.49734603, -0.01535196, ...,  0.        ,
        -0.21367048,  1.29693009],
       [ 0.71090982,  1.49734603,  0.73749508, ...,  0.        ,
         0.34215161,  1.29693009],
       [ 2.67358047,  1.49734603,  2.6838028 , ...,  0.        ,
         0.26010325,  1.29693009]])

In [82]:
from sklearn.neural_network import MLPClassifier

In [83]:
mlp = MLPClassifier(hidden_layer_sizes=(5,4,3),max_iter=500)

In [84]:
print (X_train[0])
print (type(y_train)) #Serries

mlp.fit(X_train,y_train)

[-0.39668852 -0.84213153 -0.36086913 -0.42006143 -0.66889761 -0.40706415
 -0.46966325 -0.24389106 -0.28754306 -0.27638815 -0.19555063 -0.55042026
 -0.19051504 -0.3907652  -0.17679549 -0.39430358 -0.20222914 -0.2267126
 -0.18226436 -0.80478816 -0.29833389 -0.39796776  0.         -0.34646758
 -0.77105159]
<class 'pandas.core.series.Series'>

C:\Users\yuli\AppData\Local\Continuum\Anaconda3\envs\Python35\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:563: ConvergenceWarning: Stochastic Optimizer: Maximum iterations reached and the optimization hasn't converged yet.
  % (), ConvergenceWarning)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(5, 4, 3), learning_rate='constant',
       learning_rate_init=0.001, max_iter=500, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [85]:
predictions = mlp.predict(X_test)

In [86]:
from sklearn.metrics import classification_report,confusion_matrix

print(confusion_matrix(y_test,predictions))

[[155   0   1]
 [  0  10   2]
 [  0   0  26]]

In [87]:
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

          2       1.00      0.99      1.00       156
          4       1.00      0.83      0.91        12
          6       0.90      1.00      0.95        26

avg / total       0.99      0.98      0.98       194

In [88]:
print (mlp.coefs_)

[array([[  5.16820982e-01,   2.19488913e-01,  -6.97028719e-02,
         -7.65904828e-01,  -3.91341289e-01],
       [ -1.47476366e-01,  -1.22865122e-01,   3.80326054e-01,
         -1.24257947e-01,   1.96735906e-01],
       [ -2.97919841e-01,   2.52168174e-01,   3.07389619e-01,
         -5.24934745e-01,   3.75861429e-01],
       [  2.99282978e-01,  -8.87337291e-02,   1.05179927e-01,
         -7.38200237e-01,  -3.37218082e-01],
       [  1.76024802e-01,   1.83235249e-01,   4.97254916e-01,
         -6.21227825e-01,   1.59665119e-01],
       [ -3.82086961e-01,   1.17119691e-01,  -6.93332228e-02,
         -1.53993195e-01,  -7.13549304e-01],
       [  2.29711960e-01,   6.00990594e-02,   1.11689831e-01,
         -7.95331155e-01,  -2.22720297e-03],
       [  7.86452365e-02,  -9.91059720e-02,  -2.03994357e-01,
         -2.01587241e-01,  -5.72819384e-01],
       [  6.48070526e-02,   5.92008562e-01,   3.84590968e-01,
         -7.43444827e-01,  -3.93314004e-01],
       [  2.59951069e-01,  -9.71097857e-02,  -3.30943994e-02,
         -4.01574047e-01,  -6.77568035e-01],
       [  2.94041659e-01,  -1.10629369e-01,  -2.48753040e-01,
         -2.81483288e-01,  -5.25503134e-01],
       [  4.81673247e-04,  -1.70233890e-01,   3.39192320e-01,
         -3.05233079e-01,  -2.18037954e-01],
       [ -4.72823190e-01,  -2.25994380e-01,  -1.16040699e-01,
          6.87007553e-02,  -1.86884010e-01],
       [  1.74679698e-02,   1.35537645e+00,  -5.35838536e-01,
         -5.13007061e-01,   1.02852412e-01],
       [  2.47658605e-01,  -3.34399918e-01,   1.39450734e-01,
         -1.02675058e-01,  -7.21772661e-01],
       [ -7.13006629e-03,   1.41966429e+00,   3.92984749e-02,
         -6.74085153e-01,  -5.49161555e-01],
       [ -3.25114775e-01,   7.91546005e-02,   4.03897578e-01,
         -1.42430666e-02,   1.96797477e-01],
       [  2.07257202e-01,   1.09356395e-01,   3.05970044e-01,
         -6.24346960e-01,  -3.08593623e-01],
       [ -1.56545806e-01,   1.06933249e-01,  -2.09526122e-02,
         -4.58084311e-01,  -2.25315646e-01],
       [ -3.91858691e-02,  -2.20324991e-01,   2.75287667e-01,
         -7.35883797e-01,   7.51716197e-02],
       [ -7.44016819e-02,   1.31227836e-01,   3.97996338e-01,
         -2.81327314e-01,  -3.99379455e-01],
       [ -1.89504677e-01,   8.33739598e-01,  -2.36574251e-01,
         -6.11796633e-01,  -5.69927274e-01],
       [ -3.39291879e-24,   5.72151418e-16,  -8.31915240e-10,
          4.56509904e-04,   3.21494258e-04],
       [ -6.96118615e-02,   2.14324848e-01,   2.60378877e-04,
         -1.93165351e-02,  -1.27700837e-01],
       [ -4.04509066e-01,   1.24648298e-01,   8.63340970e-01,
         -5.91645444e-01,   1.47557907e-01]]), array([[-0.51844577,  0.02742621,  0.05228986,  0.37016918],
       [-0.18342178, -0.41114182,  1.19802143, -0.07928227],
       [-0.06721889,  1.14031246, -0.4317476 ,  0.7157058 ],
       [-0.09326477,  0.85195229, -0.96842355, -0.38050632],
       [ 0.37031784,  0.51154489, -1.00736023,  0.63600279]]), array([[-0.47128026, -0.31064087,  0.24930073],
       [ 1.22612586, -0.18483357, -0.71974124],
       [-0.97716278, -0.32499984,  1.01181358],
       [ 0.35423661,  0.58335991, -0.4715755 ]]), array([[ 0.27750971, -0.9069612 , -1.12172503],
       [-0.30049737,  0.78738096,  0.49164172],
       [-1.4983389 , -0.34063597, -0.06504866]])]

In [89]:
print (mlp.coefs_[0])

[[  5.16820982e-01   2.19488913e-01  -6.97028719e-02  -7.65904828e-01
   -3.91341289e-01]
 [ -1.47476366e-01  -1.22865122e-01   3.80326054e-01  -1.24257947e-01
    1.96735906e-01]
 [ -2.97919841e-01   2.52168174e-01   3.07389619e-01  -5.24934745e-01
    3.75861429e-01]
 [  2.99282978e-01  -8.87337291e-02   1.05179927e-01  -7.38200237e-01
   -3.37218082e-01]
 [  1.76024802e-01   1.83235249e-01   4.97254916e-01  -6.21227825e-01
    1.59665119e-01]
 [ -3.82086961e-01   1.17119691e-01  -6.93332228e-02  -1.53993195e-01
   -7.13549304e-01]
 [  2.29711960e-01   6.00990594e-02   1.11689831e-01  -7.95331155e-01
   -2.22720297e-03]
 [  7.86452365e-02  -9.91059720e-02  -2.03994357e-01  -2.01587241e-01
   -5.72819384e-01]
 [  6.48070526e-02   5.92008562e-01   3.84590968e-01  -7.43444827e-01
   -3.93314004e-01]
 [  2.59951069e-01  -9.71097857e-02  -3.30943994e-02  -4.01574047e-01
   -6.77568035e-01]
 [  2.94041659e-01  -1.10629369e-01  -2.48753040e-01  -2.81483288e-01
   -5.25503134e-01]
 [  4.81673247e-04  -1.70233890e-01   3.39192320e-01  -3.05233079e-01
   -2.18037954e-01]
 [ -4.72823190e-01  -2.25994380e-01  -1.16040699e-01   6.87007553e-02
   -1.86884010e-01]
 [  1.74679698e-02   1.35537645e+00  -5.35838536e-01  -5.13007061e-01
    1.02852412e-01]
 [  2.47658605e-01  -3.34399918e-01   1.39450734e-01  -1.02675058e-01
   -7.21772661e-01]
 [ -7.13006629e-03   1.41966429e+00   3.92984749e-02  -6.74085153e-01
   -5.49161555e-01]
 [ -3.25114775e-01   7.91546005e-02   4.03897578e-01  -1.42430666e-02
    1.96797477e-01]
 [  2.07257202e-01   1.09356395e-01   3.05970044e-01  -6.24346960e-01
   -3.08593623e-01]
 [ -1.56545806e-01   1.06933249e-01  -2.09526122e-02  -4.58084311e-01
   -2.25315646e-01]
 [ -3.91858691e-02  -2.20324991e-01   2.75287667e-01  -7.35883797e-01
    7.51716197e-02]
 [ -7.44016819e-02   1.31227836e-01   3.97996338e-01  -2.81327314e-01
   -3.99379455e-01]
 [ -1.89504677e-01   8.33739598e-01  -2.36574251e-01  -6.11796633e-01
   -5.69927274e-01]
 [ -3.39291879e-24   5.72151418e-16  -8.31915240e-10   4.56509904e-04
    3.21494258e-04]
 [ -6.96118615e-02   2.14324848e-01   2.60378877e-04  -1.93165351e-02
   -1.27700837e-01]
 [ -4.04509066e-01   1.24648298e-01   8.63340970e-01  -5.91645444e-01
    1.47557907e-01]]

In [90]:
print (mlp.coefs_[1])

[[-0.51844577  0.02742621  0.05228986  0.37016918]
 [-0.18342178 -0.41114182  1.19802143 -0.07928227]
 [-0.06721889  1.14031246 -0.4317476   0.7157058 ]
 [-0.09326477  0.85195229 -0.96842355 -0.38050632]
 [ 0.37031784  0.51154489 -1.00736023  0.63600279]]

In [91]:
print (mlp.coefs_[2])

[[-0.47128026 -0.31064087  0.24930073]
 [ 1.22612586 -0.18483357 -0.71974124]
 [-0.97716278 -0.32499984  1.01181358]
 [ 0.35423661  0.58335991 -0.4715755 ]]

In [92]:
print (mlp.coefs_[3])

[[ 0.27750971 -0.9069612  -1.12172503]
 [-0.30049737  0.78738096  0.49164172]
 [-1.4983389  -0.34063597 -0.06504866]]

In [93]:
print (mlp.intercepts_[0])

[ 0.19996338  0.4578823   0.20106698  0.56603394  0.64309957]